### ISSUE TITLE
[Pitch]: Adding Jest Snapshot Testing to a React Native Windows App

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-devblog#3]
### What team are you from?

React Native Windows

### What's the title that you are thinking of for your blogpost?

Adding Jest Snapshot Testing to a React Native Windows App

### What is your blogpost about?

This blogpost will be a walkthrough of my process to add Jest Snapshot testing to a React Native Windows application (React Native Gallery). The post will cover context on the Jest testing framework, the steps I took to add tests, and troubleshooting advice on pitfalls I hit during my work. 

### First time author?

- [X] Yes, it's my first time writing for this devblog.

**Comment by kelset** [comment]
sounds good - I think that having screenshots of the work and also being able to point to an existing PR will be good to make it useful to the readers 👍

**Comment by chiaramooney** [comment]
Sounds good! Could you grant me writer access to the repo, and I can submit a PR with my post?

**Comment by kelset** [comment]
merged! https://github.com/microsoft/react-native-devblog/pull/4
